-- Migration: Add conversation_summaries table
-- Date: 2026-02-24
-- Purpose: Phase B Memory Management — store per-user Haiku-generated conversation
--          summaries so the bot has cross-session context without injecting full
--          raw history (~2K tokens) on every follow-up query.
-- Rollback: 006_add_conversation_summaries_rollback.sql

-- =============================================================================
-- 1. CREATE TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS conversation_summaries (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Who the conversation was with
    user_email  TEXT NOT NULL,
    channel_id  TEXT,                           -- Slack DM channel ID

    -- Haiku-generated summary (target ≤150 tokens)
    summary     TEXT NOT NULL,

    -- Extracted topics for future Phase C semantic retrieval
    -- e.g. ARRAY['austin.chen@fivetran.com', 'AP-Approver', 'CRITICAL']
    topics      TEXT[] DEFAULT '{}',

    -- Outcome classification
    outcome     TEXT CHECK (outcome IN ('APPROVED', 'DENIED', 'ESCALATED', 'INFO') OR outcome IS NULL),

    -- Timestamps
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ             -- created_at + 90 days, set by application
);

-- =============================================================================
-- 2. INDEXES
-- =============================================================================

-- Primary query: SELECT ... WHERE user_email = ? ORDER BY created_at DESC LIMIT 3
CREATE INDEX IF NOT EXISTS idx_conv_summaries_user_created
    ON conversation_summaries (user_email, created_at DESC);

-- TTL cleanup: DELETE WHERE expires_at < NOW()
CREATE INDEX IF NOT EXISTS idx_conv_summaries_expires
    ON conversation_summaries (expires_at)
    WHERE expires_at IS NOT NULL;

-- =============================================================================
-- 3. COMMENTS
-- =============================================================================

COMMENT ON TABLE conversation_summaries IS
    'Phase B Memory Management: per-user conversation summaries generated by Haiku '
    'after each Slack DM exchange. Injected as prior context (~150 tokens) instead '
    'of raw thread history (~2K tokens) on follow-up queries. 90-day TTL.';

COMMENT ON COLUMN conversation_summaries.summary IS
    'Haiku-generated 2-3 sentence summary of the exchange: users/roles mentioned, '
    'decision made, key facts.';

COMMENT ON COLUMN conversation_summaries.topics IS
    'Array of notable entities extracted from the conversation. '
    'Used by Phase C semantic catalogue for retrieval.';

COMMENT ON COLUMN conversation_summaries.outcome IS
    'High-level decision outcome. NULL if the exchange was informational only.';
